id: 'real2sketch'

# Model initialization
dataset: 'domainnet'
model_init: 'source'

# Number of runs
runs: 3
source: 'real'
target: 'sketch'

# Total budget
total_budget: 5000

# Number of rounds
num_rounds: 10

cnn: 'ResNet34'
warmup_epochs: 50
optimizer: 'Adam'
use_cuda: True
batch_size: 64  # for src data in CLUE

# Source training hyperparameters
lr: 0.00001
wd: 0.00001
num_epochs: 50

# UDA hyperparameters
uda_lr: 0.0000003
uda_num_epochs: 50

# DA hyperparameters
adapt_lr: 0.00001
adapt_num_epochs: 20

# Domain adaptation loss weights
src_sup_wt: 0.1
unsup_wt: 0.1
cent_wt: 0.01

# DiaNA hyperparameters
k_feat: 32
sele_conf_thred: 0.95
src_weight: 0.1
cc_weight: 0.5
uc_weight: 0.1
iter_num: 'tgt_sup_loader'

# CLUE hyperparameters
clue_softmax_t: 0.1
